#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gathio"
name = "Gathio"
description.en = "A simple, federated, privacy-first event hosting platform."
description.fr = "Une plateforme simple, fédérée et orientée confidentialité pour l'hébergment d'évènements."
version = "1.5.2~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "GPL-3.0"
website = "https://gath.io"
demo = "https://gath.io"
admindoc = "https://docs.gath.io/running-gathio/installation"
userdoc = "https://docs.gath.io/using-gathio/fediverse"
code = "https://github.com/lowercasename/gathio"
fund = "https://ko-fi.com/raphaelkabo"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/gathio"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.site_name]
    ask.en = "Instance Name"
    ask.fr = "Nom de l'instance"
    type = "string"
    default = "Gathio @YNH"

    [install.send_email_from]
    ask.en = "Contact email"
    ask.fr = "Email de contact"
    type = "email"
    #default = "contact@$domain"
    help.en = "Email address appearing the in the 'from' field of the emails Gathio sends."
    help.fr = "Adresse email apparaissant dans le champ 'expéditeur' des emails envoyés par Gathio."

    [install.delete_after_days]
    ask.en = "Number of days after which events will be deleted once they have ended."
    ask.fr = "Nombre de jours après lesquels effacer les évènements une fois qu'ils sont terminés."
    type = "number"
    default = 7
    help.en = "Set to 0 to disable automatic deletion (old events will never be deleted)."
    help.fr = "Entrez 0 pour désactiver la suppression automatique (les anciens évènements ne seront jamais effacés)."

    [install.is_federated]
    ask.en = "Enable ActivityPub federation features"
    ask.fr = "Activer les fonctionnalités de fédération ActivityPub"
    type = "boolean"
    default = "true"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This is not used as we are using git clone. It's only here for autoupdate.
        url = "https://github.com/lowercasename/gathio/archive/refs/tags/v1.5.2.tar.gz"
        sha256 = "31fd0774e4224db8ad9f45b81af523027113decf7e289cc4ea28c311488bda61"
        autoupdate.strategy = "latest_github_release"

        [resources.sources.ynh_build]
        url = "https://github.com/oleole39/gathio_ynh/releases/download/v1.5.2/gathio_v1.5.2_ynh.zip"
        sha256 = "df8634cb5bbc70f273dbc4ad0ae2e8c9fd50abbe234d91d9d5a1e35898e91f67"
        format = "zip"
        extract = true
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
